// const fs = require('fs');

// const postsGenerator = (postsNum) => {
//     const posts = [];
//     for (let i = 1; i <= postsNum; i++) {
//         posts.push({
//             id: i,
//             title: `Note ${i}`,
//             author: `Author ${i}`,
//             email: `mail_${i}@gmail.com`,
//             content: `Content for note ${i}`
//         });
//     }
//     return posts;
// };

// const postsNum = 87; 
// const data = { posts: postsGenerator(postsNum) };

// fs.writeFileSync('./data/notes.json', JSON.stringify(data, null, 2));
// console.log(`${postsNum} posts were generated by the awsome script of yuval and or`);

const fs = require('fs');

const postsGenerator = (postsNum) => {
    const posts = [];
    for (let i = 1; i <= postsNum; i++) {
        posts.push({
            id: i,
            title: `Note ${i}`,
            author: {
                name: `Author ${i}`,
                email: `mail_${i}@gmail.com`
            },
            content: `Content for note ${i}`
        });
    }
    return posts;
};

const postsNum = 87; 
const data = { notes: postsGenerator(postsNum) };

fs.writeFileSync('./data/notes.json', JSON.stringify(data, null, 2));
console.log(`${postsNum} posts were generated by the awesome script of Yuval and Or`);
